android.useAndroidX=true
android.enableJetifier=true
      - name: Extract source
        run: |
          unzip -o Drh-Mandiri-Android-Source*.zip
          ls -la
          ls -la DrhMandiri

      - name: Enable AndroidX
        working-directory: DrhMandiri
        run: |
          touch gradle.properties
          grep -qxF 'android.useAndroidX=true' gradle.properties || echo 'android.useAndroidX=true' >> gradle.properties
          grep -qxF 'android.enableJetifier=true' gradle.properties || echo 'android.enableJetifier=true' >> gradle.properties

      - name: Set up Java
